name: Build Helwan USB Binary
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0 libqt5gui5 gcc ccache binutils

      - name: Install Python Tools
        run: |
          python -m pip install --upgrade pip
          pip install nuitka==2.1 ordered-set PyQt5 

      - name: Build with Nuitka
        run: |
          # هنا بنمنع Nuitka إنها تلم ملفات الـ QML التالفة اللي بتعمل Error الـ readelf
          python -m nuitka --standalone --onefile \
                 --plugin-enable=pyqt5 \
                 --noinclude-qt-translations \
                 --nofollow-import-to=PyQt5.QtQuick \
                 --output-filename=hel-usb-writer \
                 helwan_usb_writer.py

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: helwan-binary
          path: hel-usb-writer
